# Generated by Django 6.0.7 on 2026-07-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
