# Generated by Django 6.0.7 on 2026-07-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0002_alter_empprofile_address_alter_empprofile_date_hired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empprofile',
            name='email',
        ),
    ]
