# Generated by Django 6.0.7 on 2026-07-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0003_remove_empprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='empprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
