# Generated by Django 6.0.7 on 2026-08-01 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0004_remove_empprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
