# Generated by Django 6.0.7 on 2026-08-03 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
