# Generated by Django 6.0.7 on 2026-08-05 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0009_designationmaster_rolemaster_shiftmaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empprofile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='empprofile',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='appEmp.designationmaster'),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='is_default_manager',
            field=models.BooleanField(default=False, help_text='New employees will automatically report to this employee. Only one active employee can be the default manager.'),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Reporting manager or immediate superior of this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='appEmp.empprofile'),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='appEmp.shiftmaster'),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
