# Generated by Django 6.0.7 on 2026-08-06 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0012_attendanceexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Example: Casual Leave, Sick Leave, Earned Leave.', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short unique code such as CL, SL, EL or LOP.', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=True, help_text='Uncheck for unpaid leave or loss-of-pay leave.')),
                ('allow_half_day', models.BooleanField(default=False, help_text='Allow employees to apply for half-day leave.')),
                ('requires_document', models.BooleanField(default=False, help_text='Require a supporting document while applying.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active leave types will be available for assignment and requests.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
            },
        ),
    ]
