# Generated by Django 6.0.7 on 2026-08-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0017_migrate_existing_roles_to_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empprofile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_hr_dashboard', 'Can view HR dashboard'), ('manage_employees', 'Can manage employees'), ('manage_attendance', 'Can manage attendance'), ('review_leave', 'Can review leave requests'), ('manage_leave_balance', 'Can manage leave balances'), ('review_attendance_exception', 'Can review attendance exceptions'), ('manage_salary', 'Can manage salary')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
