# Generated by Django 6.0.7 on 2026-08-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0019_assign_group_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleMaster',
        ),
        migrations.RemoveField(
            model_name='empprofile',
            name='role',
        ),
    ]
