# Generated by Django 6.0.7 on 2026-08-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0020_delete_rolemaster_remove_empprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empprofile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_hr_dashboard', 'Can view HR dashboard'), ('manage_employees', 'Can manage employees'), ('manage_attendance', 'Can manage attendance'), ('review_leave', 'Can review leave requests'), ('manage_leave_balance', 'Can manage leave balances'), ('review_attendance_exception', 'Can review attendance exceptions'), ('manage_salary', 'Can manage salary'), ('view_all_clearance_requests', 'Can view all clearance requests'), ('apply_clearance_for_employee', 'Can apply clearance for an employee'), ('review_finance_noc', 'Can review finance NOC requests'), ('initiate_employee_exit', 'Can initiate employee exit'), ('finalize_employee_exit', 'Can finalize employee exit')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
