# Generated by Django 6.0.7 on 2026-08-11 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0022_setup_finance_and_clearance_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_type', models.CharField(choices=[('NOC', 'NOC / Clearance'), ('TERMINATION', 'Termination / Exit')], default='NOC', max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('READY_FOR_FINALIZATION', 'Ready for Finalization'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearance_requests', to='appEmp.empprofile')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_requests_finalized', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clearance Request',
                'verbose_name_plural': 'Clearance Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('approval_type', models.CharField(choices=[('MANAGER_NOC', 'Manager NOC'), ('FINANCE_NOC', 'Finance NOC')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_approvals_assigned', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_approvals_decided', to=settings.AUTH_USER_MODEL)),
                ('clearance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='appEmp.clearancerequest')),
            ],
            options={
                'verbose_name': 'Clearance Approval',
                'verbose_name_plural': 'Clearance Approvals',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('clearance_request', 'approval_type'), name='unique_clearance_approval_type_per_request')],
            },
        ),
    ]
