# Generated by Django 6.0.7 on 2026-08-11 08:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0023_clearancerequest_clearanceapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exit_type', models.CharField(choices=[('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination')], max_length=20)),
                ('reason', models.TextField()),
                ('proposed_last_working_date', models.DateField(blank=True, null=True)),
                ('final_last_working_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('HR_REJECTED', 'HR Rejected'), ('CLEARANCE_IN_PROGRESS', 'Clearance In Progress'), ('READY_FOR_FINALIZATION', 'Ready for Finalization'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=30)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clearance_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_exit_request', to='appEmp.clearancerequest')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_requests', to='appEmp.empprofile')),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_exit_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_exit_requests_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Exit Request',
                'verbose_name_plural': 'Employee Exit Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
