# Generated by Django 6.0.7 on 2026-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0024_employeeexitrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexitrequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('HR_REJECTED', 'HR Rejected'), ('CLEARANCE_IN_PROGRESS', 'Clearance In Progress'), ('CLEARANCE_REJECTED', 'Clearance Rejected'), ('READY_FOR_FINALIZATION', 'Ready for Finalization'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=30),
        ),
    ]
