# Generated by Django 6.0.7 on 2026-08-11 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0025_alter_employeeexitrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeexitrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='employeeexitrequest',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeexitrequest',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_exit_requests_finalized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeexitrequest',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_exit_requests_initiated', to=settings.AUTH_USER_MODEL),
        ),
    ]
