# Generated by Django 6.0.7 on 2026-08-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0026_alter_employeeexitrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empprofile',
            name='leave_eligible_from',
            field=models.DateField(blank=True, help_text='Date from which the employee becomes eligible to use the leave facility.', null=True),
        ),
    ]
