# Generated by Django 6.0.7 on 2026-08-13 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0029_workschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='empprofile',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='appEmp.workschedule'),
        ),
    ]
