# Generated by Django 6.0.7 on 2026-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0032_optionalholidayrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(max_length=100, unique=True)),
                ('sender_wa_id', models.CharField(max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
