# Generated by Django 6.0.7 on 2026-08-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0033_whatsappticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappticket',
            name='category',
            field=models.CharField(choices=[('leave', 'Leave'), ('attendance', 'Attendance'), ('payroll', 'Payroll'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('auto_resolved', 'Auto-resolved')], default='new', max_length=20),
        ),
    ]
