# Generated by Django 6.0.7 on 2026-08-27 10:22

from django.db import migrations


DEFAULT_DOCUMENT_TYPES = [
    ("Aadhar Card", "Government-issued Aadhar identity card"),
    ("PAN Card", "Permanent Account Number card"),
    ("Resume", "Employee resume / CV"),
    ("Offer Letter", "Signed offer letter"),
]


def seed_document_types(apps, schema_editor):
    DocumentTypeMaster = apps.get_model("appEmp", "DocumentTypeMaster")

    for name, description in DEFAULT_DOCUMENT_TYPES:
        DocumentTypeMaster.objects.get_or_create(
            name=name,
            defaults={"description": description, "is_active": True}
        )


def remove_seeded_document_types(apps, schema_editor):
    DocumentTypeMaster = apps.get_model("appEmp", "DocumentTypeMaster")
    names = [name for name, _ in DEFAULT_DOCUMENT_TYPES]
    DocumentTypeMaster.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0036_documenttypemaster_empdocument'),
    ]

    operations = [
        migrations.RunPython(seed_document_types, remove_seeded_document_types),
    ]