# Generated by Django 6.0.7 on 2026-08-27 10:28

import appEmp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0037_seed_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdocument',
            name='file',
            field=models.FileField(upload_to=appEmp.models.emp_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx']), appEmp.models.validate_document_size]),
        ),
    ]
