# Generated by Django 6.0.7 on 2026-09-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0038_alter_empdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
