# Generated by Django 6.0.7 on 2026-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0039_attendance_check_in_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empprofile',
            name='aadhar_no',
            field=models.CharField(blank=True, help_text='12-digit Aadhar number.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='avsec_training_date',
            field=models.DateField(blank=True, help_text='Date of AVSEC training completion.', null=True),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='esic_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='ifsc_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='pan_no',
            field=models.CharField(blank=True, help_text='PAN number, e.g. ABCDE1234F.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='police_verification_date',
            field=models.DateField(blank=True, help_text='Date of police verification.', null=True),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='uan_no',
            field=models.CharField(blank=True, help_text='Universal Account Number (EPFO).', max_length=20, null=True),
        ),
    ]
