# Generated by Django 6.0.7 on 2026-09-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0040_empprofile_aadhar_no_empprofile_avsec_training_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeImportFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text="Internal field name, e.g. 'aadhar_no', 'email', 'full_name'.", max_length=50, unique=True)),
                ('column_label', models.CharField(help_text="Exact header text expected in the uploaded sheet, e.g. 'Aadhar No.'", max_length=100)),
                ('display_name', models.CharField(help_text='Label shown in the import preview table.', max_length=100)),
                ('target_model', models.CharField(choices=[('USER', 'User Account'), ('PROFILE', 'Employee Profile')], max_length=10)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('FULL_NAME', 'Full Name (splits into first/last)'), ('EMAIL', 'Email'), ('DATE', 'Date'), ('PHONE', 'Phone Number'), ('REGEX', 'Text (custom pattern)'), ('DESIGNATION_FK', 'Designation (lookup / create)')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('validation_regex', models.CharField(blank=True, help_text="Only used when data_type = 'Text (custom pattern)'.", max_length=200)),
                ('validation_message', models.CharField(blank=True, help_text="Error shown when validation_regex doesn't match.", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employee Import Field',
                'verbose_name_plural': 'Employee Import Fields',
                'ordering': ['order', 'field_key'],
            },
        ),
    ]
