# Generated by Django 6.0.7 on 2026-09-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmp', '0042_seed_employee_import_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_out_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
